export const UPDATE_SELECTED_CURRENCY = 'UPDATE_SELECTED_CURRENCY';
export const UPDATE_SELECTED_CURRENCY_NAME = 'UPDATE_SELECTED_CURRENCY_NAME';
export const UPDATE_CURRENCY_INDEX = 'UPDATE_CURRENCY_INDEX';
export const UPDATE_COLLATERAL_CURRENCY = 'UPDATE_COLLATERAL_CURRENCY';
export const UPDATE_COLLATERAL_CURRENCY_NAME =
    'UPDATE_COLLATERAL_CURRENCY_NAME';
export const UPDATE_COLLATERAL_CURRENCY_INDEX =
    'UPDATE_COLLATERAL_CURRENCY_INDEX';

export const UPDATE_SELECTED_TERMS = 'UPDATE_SELECTED_TERMS';
export const UPDATE_BORROW_AMOUNT = 'UPDATE_BORROW_AMOUNT';
export const UPDATE_TERMS_INDEX = 'UPDATE_TERMS_INDEX';
export const UPDATE_COLLATERAL_AMOUNT = 'UPDATE_COLLATERAL_AMOUNT';

export const UPDATE_BORROW_RATE = 'UPDATE_BORROW_RATE';

export const UPDATE_LEND_AMOUNT = 'UPDATE_LEND_AMOUNT';
export const UPDATE_LEND_RATE = 'UPDATE_LEND_RATE';
