export const FETCHING_FILECOIN_WALLET_PROVIDER =
    'FETCHING_FILECOIN_WALLET_PROVIDER';
export const FETCHING_FILECOIN_WALLET_PROVIDER_FAILURE =
    'FETCHING_FILECOIN_WALLET_PROVIDER_FAILURE';

export const UPDATE_WALLET_TYPE = 'UPDATE_WALLET_TYPE';
export const UPDATE_WALLET_PROVIDER = 'UPDATE_WALLET_PROVIDER';
export const RESET_WALLET_PROVIDER = 'RESET_WALLET_PROVIDER';
