export const FETCHING_LENDING_TERMINAL = 'FETCHING_LENDING_TERMINAL'
export const FETCHING_LENDING_TERMINAL_FAILURE = 'FETCHING_LENDING_TERMINAL_FAILURE'

export const FETCHING_ORDERBOOK = 'FETCHING_ORDERBOOK'
export const FETCHING_ORDERBOOK_FAILURE = 'FETCHING_ORDERBOOK_FAILURE'

export const FETCHING_TRADING_HISTORY = 'FETCHING_TRADING_HISTORY'
export const FETCHING_TRADING_HISTORY_FAILURE = 'FETCHING_TRADING_HISTORY_FAILURE'

export const FETCHING_BORROW_ORDERBOOK_SUCCESS = 'FETCHING_BORROW_ORDERBOOK_SUCCESS'
export const FETCHING_LEND_ORDERBOOK_SUCCESS = 'FETCHING_LEND_ORDERBOOK_SUCCESS'
export const FETCHING_TRADING_HISTORY_SUCCESS = 'FETCHING_TRADING_HISTORY_SUCCESS'

export const UPDATE_SELECTED_TERMS = 'UPDATE_SELECTED_TERMS'
export const UPDATE_TERMS_INDEX = 'UPDATE_TERMS_INDEX'

export const UPDATE_BORROW_AMOUNT = 'UPDATE_BORROW_AMOUNT'
export const UPDATE_BORROW_RATE = 'UPDATE_BORROW_RATE'

export const UPDATE_LEND_AMOUNT = 'UPDATE_LEND_AMOUNT'
export const UPDATE_LEND_RATE = 'UPDATE_LEND_RATE'

export const UPDATE_SELECTED_CURRENCY = 'UPDATE_SELECTED_CURRENCY'
export const UPDATE_SELECTED_CURRENCY_NAME = 'UPDATE_SELECTED_CURRENCY_NAME'
export const UPDATE_CURRENCY_INDEX = 'UPDATE_CURRENCY_INDEX'

export const UPDATE_MARKET_ADDRESS = 'UPDATE_MARKET_ADDRESS'
export const UPDATE_ORDERBOOK_SPREAD = 'UPDATE_ORDERBOOK_SPREAD'
export const UPDATE_ORDERBOOK_MARKET_RATE = 'UPDATE_ORDERBOOK_MARKET_RATE'
