export enum QueryKeys {
    CURRENCIES = 'CURRENCIES',
    COLLATERAL_BOOK = 'COLLATERAL_BOOK',
    LENDING_MARKETS = 'LENDING_MARKETS',
    ORDER_BOOK = 'ORDER_BOOK',
    ORDER_ESTIMATE = 'ORDER_ESTIMATE',
    ORDER_FEE = 'ORDER_FEE',
    ORDER_LIST = 'ORDER_LIST',
    POSITIONS = 'POSITIONS',
    PROTOCOL_DEPOSIT_AMOUNT = 'PROTOCOL_DEPOSIT_AMOUNT',
    TOKEN_BALANCE = 'TOKEN_BALANCE',
    USED_CURRENCIES_FOR_ORDERS = 'USED_CURRENCIES_FOR_ORDERS',
}

export const QUERIES_TO_INVALIDATE = [
    QueryKeys.COLLATERAL_BOOK,
    QueryKeys.ORDER_BOOK,
    QueryKeys.LENDING_MARKETS,
    QueryKeys.USED_CURRENCIES_FOR_ORDERS,
    QueryKeys.ORDER_LIST,
    QueryKeys.POSITIONS,
    QueryKeys.PROTOCOL_DEPOSIT_AMOUNT,
    QueryKeys.TOKEN_BALANCE,
];
