export enum QueryKeys {
    CURRENCIES = 'CURRENCIES',
    ORDER_FEE = 'ORDER_FEE',
    ORDER_LIST = 'ORDER_LIST',
    POSITIONS = 'POSITIONS',
    PROTOCOL_DEPOSIT_AMOUNT = 'PROTOCOL_DEPOSIT_AMOUNT',
    USED_CURRENCIES_FOR_ORDERS = 'USED_CURRENCIES_FOR_ORDERS',
}
