export const FETCH_COLLATERAL_FORM_STORE = 'FETCH_COLLATERAL_FORM_STORE';
export const FETCH_COLLATERAL_FORM_STORE_FAILURE =
    'FETCH_COLLATERAL_FORM_STORE_FAILURE';

export const UPDATE_CCY_INDEX_COLLATERAL_FORM =
    'UPDATE_CCY_INDEX_COLLATERAL_FORM';
export const UPDATE_CCY_NAME_COLLATERAL_FORM =
    'UPDATE_CCY_NAME_COLLATERAL_FORM';
export const UPDATE_CCY_SHORT_NAME_COLLATERAL_FORM =
    'UPDATE_CCY_SHORT_NAME_COLLATERAL_FORM';
export const UPDATE_AMOUNT_COLLATERAL_FORM = 'UPDATE_AMOUNT_COLLATERAL_FORM';
export const UPDATE_TX_FEE_COLLATERAL_FORM = 'UPDATE_TX_FEE_COLLATERAL_FORM';

export const RESET_COLLATERAL_FORM = 'RESET_COLLATERAL_FORM';
