export const FETCHING_RATES = 'FETCHING_RATES'
export const FETCHING_RATES_FAILURE = 'FETCHING_RATES_FAILURE'

export const FETCHING_BORROW_RATES_SUCCESS = 'FETCHING_BORROW_RATES_SUCCESS'
export const FETCHING_LEND_RATES_SUCCESS = 'FETCHING_LEND_RATES_SUCCESS'
export const FETCHING_MID_RATES_SUCCESS = 'FETCHING_MID_RATES_SUCCESS'
