import { getSquidWidgetIntegratorId } from './env';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const squidConfig: any = {
    integratorId: getSquidWidgetIntegratorId(),
    theme: {
        borderRadius: {
            'button-lg-primary': '1rem',
            'button-lg-secondary': '1.25rem',
            'button-lg-tertiary': '1.25rem',
            'button-md-primary': '1rem',
            'button-md-secondary': '1rem',
            'button-md-tertiary': '0.9375rem',
            container: '1.25rem',
            input: '0.8rem',
            'menu-sm': '0.65rem',
            'menu-lg': '0.65rem',
            modal: '1.5rem',
        },
        fontSize: {
            caption: '1rem',
            'body-small': '1.25rem',
            'body-medium': '1.5rem',
            'body-large': '1.75rem',
            'heading-small': '2.25rem',
            'heading-medium': '3.08125rem',
            'heading-large': '4.40625rem',
        },
        fontWeight: {
            caption: '400',
            'body-small': '400',
            'body-medium': '400',
            'body-large': '400',
            'heading-small': '400',
            'heading-medium': '400',
            'heading-large': '400',
        },
        fontFamily: {
            'squid-main': 'Inter Variable',
        },
        boxShadow: {
            container:
                '0px 2px 5px 1px rgba(0, 0, 0, 0.20), 0px 5px 20px -1px rgba(0, 0, 0, 0.33)',
        },
        color: {
            'grey-100': '#FBFBFD',
            'grey-200': '#EDEFF3',
            'grey-300': '#B9BDEA',
            'grey-400': '#A7ABBE',
            'grey-500': '#cbd5e1',
            'grey-600': '#94a3b8',
            'grey-700': '#4C515D',
            'grey-800': '#334155',
            'grey-900': '#1e293B',
            'royal-300': '#D9BEF4',
            'royal-400': '#B893EC',
            'royal-500': '#5162FF',
            'royal-600': '#8353C5',
            'royal-700': '#6B45A1',
            'status-positive': '#5CD167',
            'status-negative': '#FF658A',
            'status-partial': '#15D6E8',
            'highlight-700': '#E4FE53',
            'animation-bg': '#5162FF',
            'animation-text': '#FBFBFD',
            'button-lg-primary-bg': '#5162FF',
            'button-lg-primary-text': '#FBFBFD',
            'button-lg-secondary-bg': '#FBFBFD',
            'button-lg-secondary-text': '#292C32',
            'button-lg-tertiary-bg': '#292C32',
            'button-lg-tertiary-text': '#D1D6E0',
            'button-md-primary-bg': '#5162FF',
            'button-md-primary-text': '#FBFBFD',
            'button-md-secondary-bg': '#1e293B',
            'button-md-secondary-text': '#F8FAFC',
            'button-md-tertiary-bg': '#292C32',
            'button-md-tertiary-text': '#D1D6E0',
            'input-bg': '#1e293B',
            'input-placeholder': '#94a3b8',
            'input-text': '#E2E8F0',
            'input-selection': '#D1D6E0',
            'menu-bg': '#1e293B',
            'menu-text': '#F8FAFC',
            'menu-backdrop': '#FBFBFD1A',
            'modal-backdrop': '#1e293B',
        },
    },
    themeType: 'dark',
    apiUrl: 'https://apiplus.squidrouter.com',
    priceImpactWarnings: {
        warning: 3,
        critical: 5,
    },
    initialAssets: {
        from: {
            address: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', // USDC on Ethereum
            chainId: '1',
        },
        to: {
            address: '0x04068DA6C83AFCFA0e13ba15A6696662335D5B75', // USDC on Fantom
            chainId: '250',
        },
    },
};
