export const FETCHING_ASSET_PRICE = 'FETCHING_ASSET_PRICE'
export const FETCHING_ASSET_PRICE_FAILURE = 'FETCHING_ASSET_PRICE_FAILURE'

export const UPDATE_ETHEREUM_USD_PRICE = 'UPDATE_ETHEREUM_USD_PRICE'
export const UPDATE_FILECOIN_USD_PRICE = 'UPDATE_FILECOIN_USD_PRICE'

export const UPDATE_ETHEREUM_USD_CHANGE = 'UPDATE_ETHEREUM_USD_CHANGE'
export const UPDATE_FILECOIN_USD_CHANGE = 'UPDATE_FILECOIN_USD_CHANGE'
