name: Build and test
on:
  [push, pull_request]
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Test
        run: npm run test -- --watchAll=false
        # bad way to configure this build command.
        # this sets CI=false to not treat warnings are errors
        # TODO: remove this ASAP and fix all the warnings
      - name: Build
        run: CI=false npm run build
      - name: Build Storybook
        run: npm run build-storybook
