name: Build All

on:
  [push, pull_request]

jobs:
  build-webapp:
    name: Build Web App
    uses: ./.github/workflows/build-webapp.yml
  build-storybook:
    name: Build Storybook
    uses: ./.github/workflows/build-storybook.yml
