name: Build Storybook

on:
  workflow_call:
    inputs:
      publish:
        description: "Publish the storybook artifact to github"
        default: false
        type: boolean
        required: false
      retention-days:
        description: "Retention days for the artifact"
        default: 90
        type: number
        required: true
      package-name:
        description: "Name of the artifact to upload"
        type: string
        required: true

jobs:
  build-storybook:
    name: Build Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - name: "Setup npm"
        run: |
          npm set @secured-finance:registry=https://npm.pkg.github.com
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"
      - name: Install Dependencies
        run: npm ci
      - name: Build Storybook
        run: npm run build-storybook
      - if: ${{ inputs.publish }}
        name: Publish Storybook
        uses: actions/upload-artifact@master
        with:
          name: ${{ inputs.package-name }}
          path: storybook-static
          retention-days: ${{ inputs.retention-days }}
