name: Build Web App

on:
  workflow_call:
    inputs:
      publish:
        description: "Publish the storybook artifact to github"
        default: false
        type: boolean
        required: false
      retention-days:
        description: "Retention days for the artifact"
        default: 90
        type: number
        required: true
      package-name:
        description: "Name of the artifact to upload"
        type: string
        required: true

jobs:
  build-webapp:
    name: Build Web App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - name: Install Dependencies
        run: npm ci
      - name: Check Syntax with Prettier
        run: npm run prettier:check
      - name: Run Tests
        run: npm run test -- --watchAll=false
        # bad way to configure this build command.
        # this sets CI=false to not treat warnings are errors
        # TODO: remove this ASAP and fix all the warnings
      - name: Build Web App
        run: CI=false npm run build
      - if: ${{ inputs.publish }}
        name: Publish Web App
        uses: actions/upload-artifact@master
        with:
          name: ${{ inputs.package-name }}
          path: build
          retention-days: ${{ inputs.retention-days }}
