name: Checkout and Install

on:
  workflow_call

jobs:
  checkout-and-build:
    name: Checkout and Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
