name: Install Dependencies

on:
  workflow_call

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: npm install
