name: Create a Version and Tag It

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
        default: 'patch'
        type: choice
        options:
          - 'hotfix'
          - 'patch'
          - 'minor'
          - 'major'

jobs:
  create-version:
    name: Create Version
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.MACHINE_USER_APP_ID }}
          private_key: ${{ secrets.MACHINE_USER_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
      - name: Tag the version
        shell: bash
        run: |
          git config user.name "SF Machine User[bot]"
          git config user.email "${{ secrets.MACHINE_USER_APP_ID }}+sf-machine-user[bot]@users.noreply.github.com"
          if [ "${{ github.event.inputs.version }}" = "hotfix" ]; then
            npm version patch -m "Hotfix: %s"
          elif [ "${{ github.event.inputs.version }}" = "patch" ]; then
            npm version patch -m "Release: %s"
          elif [ "${{ github.event.inputs.version }}" = "minor" ]; then
            npm version minor -m "Release: %s"
          else
            npm version major -m "Release: %s"
          fi
          git push --follow-tags
